### ISSUE TITLE
Linker error protobuf

### ISSUE THREAD

**Issue by tonyrh** [ZeGentzy/hookey#20]
`clang++ -fPIC -std=c++11 -m32 -DNDEBUG -DEMU_RELEASE_BUILD -Ofast -o libsteam_api.so dll/network.o dll/steam_video.o dll/steam_musicremote.o dll/steam_parental.o dll/steam_gameserverstats.o dll/steam_matchmaking_servers.o dll/base.o dll/settings.o dll/item_db_loader.o dll/steam_http.o dll/steam_music.o dll/steam_apps.o dll/steam_applist.o dll/dll.o dll/steam_screenshots.o dll/steam_client.o dll/settings_parser.o dll/flat.o dll/local_storage.o dll/steam_gameserver.o dll/net.pb.o -shared -lprotobuf-lite -Wl,--no-undefined -m32 -lpthread

/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libprotobuf-lite.so when searching for -lprotobuf-lite

/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libprotobuf-lite.a when searching for -lprotobuf-lite

/usr/bin/ld: cannot find -lprotobuf-lite

clang: error: linker command failed with exit code 1 (use -v to see invocation)

make: *** [Makefile:47: libsteam_api.so] Error 1
`

This is in Ubuntu 20.04. I installed libprotobuf-dev and protobuf-compiler but it seems like they are not the right version...

**Comment by stevenkie** [comment]
I assume you are using the steam version on this.
after copying the dlc into the /apps/[game]/dlc folder try changing the **vars[GOLDBERG_BUILD]=$'"release32"** into **vars[GOLDBERG_BUILD]=$'"release"' '** then rerun the ./install_copy.

I assume you are using this for ck 2 also. if you try ./run it will fail but, if you check your launcher on steam all dlc should be unlocked.

**Comment by tonyrh** [comment]
You assume right and your suggestion worked like a charm, thank you!

**Comment by mysoundmagic** [comment]
hello there. i had same error like above
i was try to change vars[GOLDBERG_BUILD]=$'"release32" into vars[GOLDBERG_BUILD]=$'"release"' ' then rerun the ./install_copy

but give me error:
```
/usr/bin/ld: dll/net.pb.o:(.data+0xf8): undefined reference to `google::protobuf::internal::kGlobalEmptyTable'
/usr/bin/ld: dll/net.pb.o:(.data+0x170): undefined reference to `google::protobuf::internal::kGlobalEmptyTable'
/usr/bin/ld: dll/net.pb.o:(.data+0x228): undefined reference to `google::protobuf::internal::kGlobalEmptyTable'
/usr/bin/ld: dll/net.pb.o:(.data+0x370): undefined reference to `google::protobuf::internal::kGlobalEmptyTable'
/usr/bin/ld: dll/net.pb.o:(.data+0x458): undefined reference to `google::protobuf::internal::kGlobalEmptyTable'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:47: libsteam_api.so] Error 1
+./install:8> exit 2
+./install_copy:11> exit 2
```
ubuntu 20.04 and libprotoc 3.15.6

**Comment by ga-chiacchio** [comment]
> I assume you are using the steam version on this. after copying the dlc into the /apps/[game]/dlc folder try changing the **vars[GOLDBERG_BUILD]=$'"release32"** into **vars[GOLDBERG_BUILD]=$'"release"' '** then rerun the ./install_copy.

I'm struggling with it. Where am i supposed to change **vars[GOLDBERG_BUILD]**?
