### ISSUE TITLE
Unable to run choose

### ISSUE THREAD

**Issue by Partycrank** [ZeGentzy/hookey#8]
Installed latest version of zsh, and I've followed the instructions to update the submodules. I can run the add file without any issues, when I run the choose file my terminal is filled with this: https://pastebin.com/BrGfb7ww

I'm running pop-os, not sure if that will affect things. Have you got any idea on what I could do to fix this?

Thank you!

**Comment by goddessfreya** [comment]
That's just debugging info in case something went wrong. Since the script still returned 0, it succeed.
